# Generated by Django 6.0.5 on 2026-05-17 12:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='couple', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_dinners', to='dinner.couple')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MenuTeaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_hint', models.TextField(blank=True)),
                ('main_hint', models.TextField(blank=True)),
                ('dessert_hint', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dinner_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaser', to='dinner.dinnerdate')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('atmosphere_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('decoration_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('dinner_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='dinner.dinnerdate')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_scores', to='dinner.couple')),
            ],
            options={
                'unique_together': {('dinner_date', 'scorer')},
            },
        ),
    ]
