# Generated by Django 6.0.5 on 2026-05-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='dinner.couple')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('couple', 'date')},
            },
        ),
    ]
