# Generated by Django 6.0.5 on 2026-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0003_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuteaser',
            name='dessert_hint',
        ),
        migrations.RemoveField(
            model_name='menuteaser',
            name='main_hint',
        ),
        migrations.RemoveField(
            model_name='menuteaser',
            name='starter_hint',
        ),
        migrations.AddField(
            model_name='menuteaser',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
